title: Interactive Fiction map

section: Map section 1
width: 2
height: 2

room: 3
name: R4
rpos: 0 0

room: 2
name: R3
rpos: 1 0

room: 1
name: R2
rpos: 1 1

room: 0
name: R1
rpos: 0 1

link: 0 1
lpos: 0 1
lpos: 1 1

link: 1 2
lpos: 1 1
lpos: 1 0

link: 2 3
lpos: 1 0
lpos: 0 0

link: 3 0
lpos: 0 0
lpos: 0 1

task: 5
name: Move to R2
room: 1
cmd: E

task: 6
name: Move to R3
room: 2
cmd: S

task: 7
name: Move to R4
room: 3
cmd: W

task: 4
name: Win
room: 3
