title: Interactive Fiction map

section: Map section 1
width: 2
height: 2

room: 3
name: Bedroom
rpos: 1 1

room: 2
name: Landing
rpos: 0 1

room: 1
name: Kitchen
rpos: 1 0

room: 0
name: Lounge
rpos: 0 0

link: 0 1
lpos: 0 0
lpos: 1 0

link: 0 2
lpos: 0 0
lpos: 0 1
go: U

link: 2 3
lpos: 0 1
lpos: 1 1

item: 0
name: broom
tag: broom
room: 1
finish: 1
needed: 6

task: 7
name: Move to Kitchen
room: 1
cmd: E

task: 4
name: Get broom
room: 1
note: Finishes the game
